export const Keys = {
    LOGIN: "Login",
    FORGOT: "Forgot",
    VERIFY_OTP: "VerifyOtp",
    ADMIN_PROFILE: "AdminProfile",
    CHANGE_PASSWORD: "ChangePassword",
    USER_LIST: "UserList",
    PRODUCT_LIST: "ProductList",
    DELETE_PRODUCT: "DeleteProduct",
    ADD_PRODUCT: "AddProduct",
    ADD_COLOR: "AddColor",
    FEATURED_PRODUCT_LIST: "FeaturedProductList",
    DELETE_FEATURED_PRODUCT: "DeleteFeaturedProduct",
    ADD_FEATURED_PRODUCT: "AddFeaturedProduct",
};
